version: 2
updates:
  - package-ecosystem: 'github-actions'
    # default location of '.github/workflows'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'gradle'
    directory: 'src/server/android/driver'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'gradle'
    directory: 'src/server/android/driver/app'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'npm'
    directory: ''
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'npm'
    directory: '.github/dummy-package-files-for-dependents-analytics/playwright'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'npm'
    directory: '.github/dummy-package-files-for-dependents-analytics/playwright-chromium'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'npm'
    directory: '.github/dummy-package-files-for-dependents-analytics/playwright-core'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'npm'
    directory: '.github/dummy-package-files-for-dependents-analytics/playwright-firefox'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'npm'
    directory: '.github/dummy-package-files-for-dependents-analytics/playwright-webkit'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'npm'
    directory: 'utils/flakiness-dashboard'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

# Built with ‚ù§ by [Pipeline Foundation](https://pipeline.foundation)
