language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "npm run build"
  - "npm run unit"
  - "npm run funit"
  - "npm run wunit"
jobs:
  include:
    - node_js: "10.17.0"
