version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:dev
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "browsers.json" }}

      - run:
          command: npm ci

      - run:
          command: npm run build

      - save_cache:
          key: dependency-cache-{{ checksum "browsers.json" }}
          paths:
            - $HOME/.cache/ms-playwright

      - run:
          command: |
            xvfb-run --auto-servernum npm run jest -- --testTimeout=30000
          environment:
            BROWSER: chromium

      - run:
          command: |
            xvfb-run --auto-servernum npm run jest -- --testTimeout=30000
          environment:
            BROWSER: webkit
