name: "devrelease:docker"

on:
  push:
    branches:
      - master
      - release-*
    paths:
      - docs/docker/**
      - browsers.json
      - .github/workflows/publish_canary_docker.yml

jobs:
  publish-canary-docker:
    name: "publish to DockerHub"
    # We use `docker push --all-tags` to push all tags which is a newly addition to docker
    runs-on: ubuntu-20.04
    if: github.repository == 'microsoft/playwright'
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: playwright.azurecr.io
        username: playwright
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: microsoft/playwright-github-action@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm ci
    - run: npm run build
    - run: ./docs/docker/build.sh
    - name: tag & publish
      run: |
        docker tag playwright:localbuild playwright.azurecr.io/public/playwright:next
        docker tag playwright:localbuild playwright.azurecr.io/public/playwright:sha-${{ github.sha }}
        docker push --all-tags playwright.azurecr.io/public/playwright

