name: "devrelease:npm"

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"
  push:
    branches:
      - release-*

jobs:
  publish-canary-npm:
    name: "publish to NPM"
    runs-on: ubuntu-20.04
    if: github.repository == 'microsoft/playwright'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build
    - run: node lib/cli/cli install-deps
    - run: node utils/build/update_canary_version.js --today-date
      if: contains(github.ref, 'master') && github.event_name != 'workflow_dispatch'
    - run: node utils/build/update_canary_version.js --commit-timestamp
      if: contains(github.ref, 'release') || github.event_name == 'workflow_dispatch'
    - run: utils/publish_all_packages.sh --tip-of-tree
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

