name: "release"

on:
  release:
    types: [published]

env:
  CI: true

jobs:
  publish-npm-release:
    name: "publish to NPM"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://registry.npmjs.org'
    - uses: microsoft/playwright-github-action@v1.4.2
    - run: npm ci
    - run: npm run build
    - run: utils/publish_all_packages.sh --release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-docker-release:
    name: "publish to DockerHub"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm ci
    - run: npm run build
    - run: ./docs/docker/build.sh --prepare-context
    - uses: docker/build-push-action@v1
      with:
        username: playwright
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: playwright.azurecr.io
        repository: public/playwright
        path: docs/docker/
        dockerfile: docs/docker/Dockerfile.bionic
        tags: bionic,latest
        tag_with_ref: true
