name: "Firefox Beta Builder"

on:
  push:
    branches:
      - master
      - release-*
    paths:
      - browser_patches/firefox-beta/BUILD_NUMBER
      - .github/workflows/trigger_build_firefox_beta.yml

jobs:
  trigger:
    name: "trigger"
    runs-on: ubuntu-20.04
    steps:
    - run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GH_TOKEN}" \
          --data '{"event_type": "build_firefox_beta"}' \
          https://api.github.com/repos/microsoft/playwright-internal/dispatches
      env:
        GH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_PERSONAL_ACCESS_TOKEN }}
