name: "Internal Tests"

on:
  push:
    branches:
      - main
      - release-*

jobs:
  trigger:
    name: "trigger"
    runs-on: ubuntu-20.04
    steps:
    - run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GH_TOKEN}" \
          --data "{\"event_type\": \"playwright_tests\", \"client_payload\": {\"ref\": \"${GITHUB_SHA}\"}}" \
          https://api.github.com/repos/microsoft/playwright-browsers/dispatches
      env:
        GH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_PERSONAL_ACCESS_TOKEN }}
