name: "Chromium With Symbols Builder"


on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  trigger:
    name: "trigger"
    runs-on: ubuntu-20.04
    steps:
    - run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GH_TOKEN}" \
          --data '{"event_type": "build_chromium_with_symbols"}' \
          https://api.github.com/repos/microsoft/playwright-internal/dispatches
      env:
        GH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_PERSONAL_ACCESS_TOKEN }}
